[package]
name = "bdk_floresta"
version = "0.1.0"
description = "A Floresta-powered chain-source crate for BDK"
authors = ["Luis Schwab <luisschwab@protonmail.com>"]
keywords = ["bitcoin", "bdk", "floresta", "utreexo"]
repository = "https://github.com/luisschwab/bdk-floresta"
readme = "README.md"
license = "MIT"
edition = "2021"
rust-version = "1.81.0"

[features]
default = ["logger"]
logger = ["dep:tracing-appender", "dep:tracing-subscriber"]

[[example]]
name = "block_wallet_sync"
path = "examples/block_wallet_sync/src/main.rs"

[[example]]
name = "node"
path = "examples/node/src/main.rs"

[build-dependencies]
toml = "0.9.6"

[dependencies]
bitcoin = "0.32.8"
bdk_wallet = "2.2.0"
floresta-chain = { git = "https://github.com/getfloresta/Floresta.git", rev = "87e33b0381db516ee40bfc0ce0f838137eec5dfc", features = ["flat-chainstore"] }
floresta-compact-filters = { git = "https://github.com/getfloresta/Floresta.git", rev = "87e33b0381db516ee40bfc0ce0f838137eec5dfc" }
floresta-mempool = { git = "https://github.com/getfloresta/Floresta.git", rev = "87e33b0381db516ee40bfc0ce0f838137eec5dfc" }
floresta-wire = { git = "https://github.com/getfloresta/Floresta.git", rev = "87e33b0381db516ee40bfc0ce0f838137eec5dfc" }
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["rt", "signal", "sync", "time"] }
tracing = "0.1.41"
tracing-appender = { version = "0.2.3", optional = true }
tracing-subscriber = { version = "0.3.20", features = ["ansi", "chrono", "env-filter"], optional = true }

[dev-dependencies]
anyhow = "1.0.100"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
