[package]
name = "bdk_floresta"
version = "0.1.0"
description = "A Floresta-powered chain-source crate for BDK"
authors = ["Luis Schwab <luisschwab@protonmail.com>"]
keywords = ["bitcoin", "bdk", "floresta", "utreexo"]
repository = "https://github.com/luisschwab/bdk-floresta"
readme = "README.md"
license = "MIT"
edition = "2021"
rust-version = "1.81.0"

[dependencies]
bitcoin = "0.32.8"
bdk_wallet = "2.2.0"
floresta-chain = { git = "https://github.com/getfloresta/Floresta.git", rev = "bc4115bf77b96d75e5340bcfb0061cab6f29ef9c", features = ["flat-chainstore"] }
floresta-wire = { git = "https://github.com/getfloresta/Floresta.git", rev = "bc4115bf77b96d75e5340bcfb0061cab6f29ef9c" }
floresta-compact-filters = { git = "https://github.com/getfloresta/Floresta.git", rev = "bc4115bf77b96d75e5340bcfb0061cab6f29ef9c" }
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.20", features = ["ansi", "chrono", "env-filter"] }

[build-dependencies]
toml = "0.9.6"

[dev-dependencies]
anyhow = "1.0.100"

[[example]]
name = "block_wallet_sync"
path = "examples/block_wallet_sync/src/main.rs"

[[example]]
name = "playground"
path = "examples/playground/src/main.rs"
