[package]
name = "bdk_floresta"
version = "0.1.0"
edition = "2021"
authors = ["Luis Schwab <luisschwab@protonmail.com>"]
description = "A Floresta-powered chain-source crate for BDK"
license = "MIT"
repository = "https://github.com/luisschwab/bdk-floresta"
readme = "README.md"
keywords = ["bitcoin", "bdk", "floresta", "utreexo"]

[dependencies]
bitcoin = "0.32.8"
bdk_wallet = "2.2.0"
floresta-chain = { git = "https://github.com/getfloresta/Floresta.git", rev = "37608de0b602c5b369c33e63589f6aa939ebcc8f", features = ["flat-chainstore"] }
floresta-wire = { git = "https://github.com/getfloresta/Floresta.git", rev = "37608de0b602c5b369c33e63589f6aa939ebcc8f" }
floresta-compact-filters = { git = "https://github.com/getfloresta/Floresta.git", rev = "37608de0b602c5b369c33e63589f6aa939ebcc8f" }
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.20", features = ["ansi", "chrono", "env-filter"] }

[build-dependencies]
toml = "0.9.6"

[dev-dependencies]
anyhow = "1.0.100"

[[example]]
name = "block_wallet_sync"
path = "examples/block_wallet_sync/src/main.rs"

[[example]]
name = "playground"
path = "examples/playground/src/main.rs"
